### PR TITLE
Support next 11

### PR DESCRIPTION
**Pull request by willheslam**
Next 11 has been released https://github.com/vercel/next.js/releases/tag/v11.0.0
so here's a PR to support it! :)

### CODE REVIEW

**Comment by dan2kx** [comment]
when will this go in?

**Comment by EvertLagerberg** [comment]
Also waiting for this

**Comment by lifeiscontent** [comment]
Hey guys, sorry for the wait, just saw the notification, I'll try to cut a release later tonight, thanks @willheslam for the PR

**Comment by lifeiscontent** [comment]
Sorry guys, I've tried to fix it, it seems in Next.js 11 every time I try to render a story it gives me an error saying: `router is null`

I've posted a discussion in next.js repo here; https://github.com/vercel/next.js/discussions/26964

if any of you wants to take a stab at it go ahead, PRs are welcome but I'm currently not sure how to make the plugin work with Next.js 11

@willheslam @dan2kx @EvertLagerberg

**Comment by willheslam** [comment]
Thanks for looking into this @lifeiscontent, I really appreciate it!

FWIW I haven't noticed any problems in a large-ish project I tried next 11 with. Maybe I've missed something important?
Doing `npm install next@latest --legacy-peer-deps` to override npm's complaint about storybook-addon-next-router's peer dep requirement, i.e. with the following deps:
```
    "next": "^11.0.1",
```
and following dev deps:
```
    "@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/react": "^6.3.2",
    "storybook-addon-next-router": "^2.0.4",
```

then the stories that use storybook-addon-next-router seem to behave just fine - both in storybook dev mode and in the built production mode.

My setup looks like this:
```
import type {Story, Meta} from "@storybook/react"
import {withNextRouter} from "storybook-addon-next-router"

import MyComponent from "../my-component"
import type {Props} from "../my-component"

export default {
  title: "MyComponent",
  component: MyComponent,
  decorators: [withNextRouter],
  argTypes: {
    backgroundColor: {control: "color"},
  },
} as Meta

const Template: Story<Props> = (args) => <MyComponent {...args} />

const parameters = {
  nextRouter: {
    path: "/example/[id]",
    asPath: "/example/foobar",
    query: {
      id: "foobar",
    },
  },
}

export const Example = Template.bind({})
Example.parameters = parameters
```

and the component being
```
import {useRouter} from "next/router"

export default function Example(props: Props): JSX.Element {
  const router = useRouter()

  console.log("Router", router)
  ...
  ```
  
  The story, when loaded up, logs this to the console:
 ```
 Router {route: "/", pathname: "/", query: {…}, asPath: "/example/foobar", push: ƒ, …}
 ```
 and otherwise behaves normally.
 
 If you have a repo (I realise I'm the one who created the PR, sorry :P) that shows the problem I'd be happy to try it out on my end - if I get the time this week I will try creating a minimal project that just using next 11 and storybook-addon-next-router to see if I can replicate the problem.

**Comment by lifeiscontent** [comment]
@willheslam you can find the issue I'm experiencing in my real world repo, otherwise you can play with the alpha I published earlier today

**Comment by lifeiscontent** [comment]
@willheslam any updates on this one? I've just published another release under the `next` tag, but still seems to be broken.

**Comment by orbiteleven** [comment]
@willheslam curious that you're using `decorators: [withNextRouter]` in your `export default`; I get an error when trying to do that. Not sure if it's all related, but I'm having the same (or a similar) problem as @lifeiscontent.

**Comment by HosseinAgha** [comment]
@lifeiscontent how could you resolve the `router is null` issue in your repo?

**Comment by lifeiscontent** [comment]
@HosseinAgha you should not be using the decorator directly, just pass the RouterContext.Provider via parameters as outlined in the docs, if you're having issues and you're following the README please open an issue ideally with a reproduction so I can help debug.

**Pull request merged**
