### PR TITLE
add: next13

### PR DESCRIPTION
**Pull request by mi-upto**
I wanted to use this plugin in my Next13 + Storybook project,
but I could not install it because could not resolve the dependency.

I added Next13 to this add-on.
It worked fine on the Next13 + Storybook project.

----
#66

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@mi-upto did you test this change? if so, I'll merge.

**Comment by mi-upto** [comment]
@lifeiscontent 
yeah, tested with Storybook 6.5.13 and, next 13.0.1 :dog:

**Comment by kristian240** [comment]
I can also confirm that everything works with Next 13.

**Comment by kristian240** [comment]
@lifeiscontent any news about this becoming a release?

**Comment by diginikkari** [comment]
There is issue #68 with nextjs 13. That's only one I have noticed.

**Comment by kristian240** [comment]
I already forgot about this issue, but I was able to solve this. What I did is I added

```
	env: (config) => ({
		...config,
		__NEXT_NEW_LINK_BEHAVIOR: JSON.stringify(true),
	}),
```

in my `main.js` file. I don not have any experience with writing storybook addon but is there a way to add this config in this addon?

**Comment by diginikkari** [comment]
Just to add also in case someone is looking for it. To do the same with storybook viteBuilder add following to your ´viteFinal´ config:

``` typescript
  viteFinal: async (config, options) => {
    // Merge custom configuration into the default config
    return mergeConfig(config, {
      // Use the same "resolve" configuration as your app
      define: {
        'process.env': {
          __NEXT_NEW_LINK_BEHAVIOR: true,
        },
      },
  }
```

**Comment by mattvb91** [comment]
@lifeiscontent any chance of getting this in?

**Comment by rafelis1997** [comment]
would be awesome to have this this week

**Comment by RowinVanAmsterdam** [comment]
> env: (config) => ({
> 		...config,
> 		__NEXT_NEW_LINK_BEHAVIOR: JSON.stringify(true),
> 	}),

This works for me as a temporary work-around rn, thanks!

**Comment by lifeiscontent** [comment]
Hey guys, sorry about the wait, I've been busy with other things, but just released a new version, please check out v4.0.2.

Thanks to @mi-upto for the PR!

CC: @kristian240 @diginikkari @mattvb91

**Comment by kristian240** [comment]
In the future we might not need this package at all: https://storybook.js.org/blog/integrate-nextjs-and-storybook-automatically/

**Comment by lifeiscontent** [comment]
@kristian240 yep, that's right. The storybook team has combined the work between myself and another engineer who works on a similar addon to help ease the integration with next.js.

**Pull request merged**
