### PR TITLE
Add React v18 support

### LINKED ISSUE #56: Update peer dependencies to support React 18.x.x
This Storybook addon does not have React 18 as a peer-dependency which can cause some warnings.

### PR DESCRIPTION
**Pull request by alex-ahumada**
Storybook v6.5 will support React v18.
Adding react and react-dom ^18.0.0 as peerDependencies will avoid dependency conflicts.

Tested with Storybook 6.5.0-alpha.64, should work with 6.5.0 release.

resolves #56

### CODE REVIEW

**Comment by caiotracera** [comment]
any estimate of when we will have this PR merged?

**Comment by jebadirad** [comment]
+1 looking to upgrade to react 18 and this is the only thing holding me back.  @lifeiscontent

**Comment by alex-ahumada** [comment]
Tested with Storybook 6.5.0 release.

**Comment by TomFreudenberg** [comment]
+1 looking for react18 support

**Comment by jebadirad** [comment]
for anyone else looking to move past this, we decided to switch to https://github.com/RyanClementsHax/storybook-addon-next

**Comment by lifeiscontent** [comment]
@TomFreudenberg @alex-ahumada @jebadirad @caiotracera merged and published in 4.0.0 release

**Pull request merged**
